Add email list signup link
canonical/summit.ubuntu.com pull request #8
Opened 2022-08-09 15:05 UTC by petesfrench

## Done

Add email list signup link

## QA

The sign up page has been tested but you can fill it in again and I can manually check it went through.

## Issue / Card

https://github.com/canonical/summit.ubuntu.com/issues/7

2022-08-09 15:05 UTC, webteam-app commented
Demo starting at https://summit-ubuntu-com-8.demos.haus

2022-08-10 14:21 UTC, sowasred2012 requested changes

2022-08-10 14:21 UTC, sowasred2012 commented on src/index.html
> +      <p>Registration will open on <strong>Sep 5, 2022</strong> at this location. Craving for more information? Sign up for updates here: <a href="https://lists.ubuntu.com/mailman/listinfo/summit-new
I don't think we should show raw URLs like that, it doesn't look nice and will mean very little to screen readers - plus, we basically have a CTA there in the text:

```suggestion
      <p>Registration will open on <strong>Sep 5, 2022</strong> at this location. Craving for more information?  <a href="https://lists.ubuntu.com/mailman/listinfo/summit-news">Sign up for updates here</a>.</p>
```

2022-08-10 15:53 UTC, merged

2022-08-10 16:02 UTC, sowasred2012 commented
@petesfrench as far as I can see this wasn't re-reviewed and approved, why was it merged?

2022-08-11 07:40 UTC, petesfrench commented
@sowasred2012 Sorry, that was my mistake. It was an urgent change that I wanted to get ASAP. If there are other changes needed I can make another PR.